version: '3.8'
name: pi-videogames

services:
    db:
        container_name: db-henry-games
        restart: always
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=videogames
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-db:/var/lib/postgresql/data
        networks:
            - henrygames-network

    api:
        container_name: api-henry-games
        restart: unless-stopped
        image: api-henry-games:1.0.0
        env_file: ./api/.env
        environment:
            - DB_HOST=db
        build:
            context: api
            target: API-HenryGames
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db
        networks:
            - henrygames-network

    client:
        container_name: client-henry-games
        restart: unless-stopped
        image: client-henry-games:1.0.0
        build:
            context: client
            target: CLIENT-HenryGames
            dockerfile: Dockerfile
        ports:
            - '4173:4173'
        depends_on:
            - api
        networks:
            - henrygames-network

networks:
    henrygames-network:
