version: '3.8'
name: pi-videogames

services:
    api:
        container_name: api-henry-games
        restart: unless-stopped
        image: api-henry-games:1.0.0
        environment:
            - DB_HOST=postgres-db
        build:
            context: api
            target: API-HenryGames
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            - default

    client:
        container_name: client-henry-games
        restart: unless-stopped
        image: client-henry-games:1.0.0
        build:
            context: client
            target: CLIENT-HenryGames
            dockerfile: Dockerfile
        env_file:
            - stack.env
        ports:
            - '4173:4173'
        depends_on:
            - api
        networks:
            - default

networks:
    default:
        name: traefik_network
        external: true
