version: '3.8'
name: pi-videogames

services:
    api:
        container_name: api-henry-games
        restart: unless-stopped
        image: api-henry-games:1.0.0
        build:
            context: api
            target: API-HenryGames
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - stack.env
        networks:
            - proxy_network

    client:
        container_name: client-henry-games
        restart: unless-stopped
        image: client-henry-games:1.0.0
        build:
            context: client
            target: CLIENT-HenryGames
            dockerfile: Dockerfile
        ports:
            - '4173:4173'
        environment:
            - VITE_API=https://henrygames.pinol.site
            - VITE_PORTFOLIO=https://pinol.lat
        depends_on:
            - api
        networks:
            - proxy_network

networks:
    proxy_network:
        external: true
