export const ASCENDENTE = 'ascendente'
export const DEFAULT = 'default'
export const DESCENDENTE = 'descendente'
export const EXTERNAL_API = 'EXTERNAL_API'
export const DATABASE_GAMES = 'DATABASE_GAMES'
export const API_HOST = 'http://localhost:3000'
