export const ASCENDENTE = 'ascendente'
export const DEFAULT = 'default'
export const DESCENDENTE = 'descendente'
export const EXTERNAL_API = 'EXTERNAL_API'
export const DATABASE_GAMES = 'DATABASE_GAMES'
export const DEV_API_HOST = 'http://localhost:3000'
export const PROD_API_HOST = 'https://henrygames.pinol.site'
export const PORTFOLIO_URL = 'https://pinol.lat'
