version: '3.8'
name: henrygames

services:
    api:
        container_name: api-henrygames
        restart: unless-stopped
        image: api-henrygames
        ports:
            - '3000:3000'
        networks:
            - tunnel

networks:
    tunnel:
        name: tunnel
        external: true
