version: '3.8'

services:
    api:
        container_name: henrygames
        restart: unless-stopped
        image: api-henrygames
        env_file: stack.env
        ports:
            - '3000:3000'
        networks:
            - tunnel
        build:
            context: .
            target: API-HenryGames
            dockerfile: Dockerfile

networks:
    tunnel:
        name: tunnel
        external: true
